# Generated by Django 4.0.4 on 2023-06-23 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uniformes',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.uniformes'),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='ropa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.ropa'),
        ),
        migrations.AddField(
            model_name='uniforme',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tallas'),
        ),
        migrations.AddField(
            model_name='tallas',
            name='ropa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.ropa'),
        ),
        migrations.AddField(
            model_name='subproyecto',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='status',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.civil'),
        ),
        migrations.AddField(
            model_name='status',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.nivel'),
        ),
        migrations.AddField(
            model_name='status',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil'),
        ),
        migrations.AddField(
            model_name='status',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.puesto'),
        ),
        migrations.AddField(
            model_name='status',
            name='registro_patronal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.registropatronal'),
        ),
        migrations.AddField(
            model_name='status',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sexo'),
        ),
        migrations.AddField(
            model_name='status',
            name='tipo_de_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.contrato'),
        ),
        migrations.AddField(
            model_name='status',
            name='tipo_sangre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sangre'),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='asunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.trabajos_encomendados'),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='temas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.temas_comentario_solicitud_vacaciones'),
        ),
        migrations.AddField(
            model_name='solicitud_economicos',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='ropa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.ropa'),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='registropatronal',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='subproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.subproyecto'),
        ),
        migrations.AddField(
            model_name='historicalvacaciones',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='historicalvacaciones',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvacaciones',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='historicaluniformes',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluniformes',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='estado_civil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.civil'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='nivel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.nivel'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='perfil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.perfil'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='puesto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.puesto'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='registro_patronal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.registropatronal'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='sexo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.sexo'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='tipo_de_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.contrato'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='tipo_sangre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.sangre'),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='distrito',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.distrito'),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.empresa'),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='subproyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.subproyecto'),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='historicaldatosbancarios',
            name='banco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.banco'),
        ),
        migrations.AddField(
            model_name='historicaldatosbancarios',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatosbancarios',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='historicalbonos',
            name='costo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.costo'),
        ),
        migrations.AddField(
            model_name='historicalbonos',
            name='datosbancarios',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.datosbancarios'),
        ),
        migrations.AddField(
            model_name='historicalbonos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='economicos',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='datosbancarios',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.banco'),
        ),
        migrations.AddField(
            model_name='datosbancarios',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AddField(
            model_name='costo',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status'),
        ),
        migrations.AlterUniqueTogether(
            name='catorcenas',
            unique_together={('catorcena', 'fecha_inicial')},
        ),
        migrations.AddField(
            model_name='bonos',
            name='costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.costo'),
        ),
        migrations.AddField(
            model_name='bonos',
            name='datosbancarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosbancarios'),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together={('numero_de_trabajador', 'distrito')},
        ),
    ]
