# Generated by Django 4.0.4 on 2023-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperfil',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
