# Generated by Django 4.0.4 on 2023-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_historicalperfil_editado_alter_perfil_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbancarios',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldatosbancarios',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='status',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bonos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='costo',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='economicos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalbonos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcosto',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaleconomicos',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
