# Generated by Django 3.2.3 on 2022-09-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_tallas_ropa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropatronal',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
    ]
