# Generated by Django 4.0.4 on 2023-06-27 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_datosbancarios_editado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='razon_no_autorizado',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
