# Generated by Django 3.2.3 on 2022-09-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_bancarios_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costo',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='historicalcosto',
            name='seccion',
        ),
    ]
