# Generated by Django 3.2.3 on 2022-09-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20220926_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='seccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='seccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='numero_de_tarjeta',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
