# Generated by Django 3.2.3 on 2022-10-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_alter_datosbancarios_numero_de_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicos',
            name='comentario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='economicos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='comentario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
