# Generated by Django 3.2.3 on 2022-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20221001_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicos',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleconomicos',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
