# Generated by Django 3.2.3 on 2022-10-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_auto_20221002_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicos',
            name='dias_pendientes',
        ),
        migrations.RemoveField(
            model_name='historicaleconomicos',
            name='dias_pendientes',
        ),
    ]
