# Generated by Django 3.2.3 on 2022-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20221002_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicaleconomicos',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='economicos',
            name='dias_pendientes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='dias_pendientes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
