# Generated by Django 3.2.3 on 2022-10-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20221002_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicos',
            name='aparecer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='aparecer',
            field=models.BooleanField(default=False),
        ),
    ]
