# Generated by Django 3.2.3 on 2022-10-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20221002_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicos',
            name='aparecer',
        ),
        migrations.RemoveField(
            model_name='historicaleconomicos',
            name='aparecer',
        ),
    ]
