# Generated by Django 3.2.3 on 2022-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20221002_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvacaciones',
            name='comentario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='comentario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
