# Generated by Django 4.1.1 on 2022-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_remove_userdatos_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
