# Generated by Django 4.1.1 on 2022-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_tipoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperfil',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
