# Generated by Django 4.1.1 on 2022-12-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0022_tipoperfil_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatos',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoperfil'),
        ),
    ]
