# Generated by Django 4.1.1 on 2022-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0023_userdatos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperfil',
            name='numero_de_trabajador',
            field=models.IntegerField(null=True),
        ),
    ]
