# Generated by Django 4.1.1 on 2022-12-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0025_remove_tipoperfil_numero_de_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatos',
            name='numero_de_trabajador',
            field=models.IntegerField(null=True),
        ),
    ]
