# Generated by Django 4.1.1 on 2022-12-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0028_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='regimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.regimen'),
        ),
    ]
