# Generated by Django 4.1.1 on 2022-12-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0030_tablafestivos_alter_status_regimen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablafestivos',
            old_name='fecha_nacimiento',
            new_name='dia_festivo',
        ),
    ]
