# Generated by Django 4.1.1 on 2022-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0031_rename_fecha_nacimiento_tablafestivos_dia_festivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimen',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='viernes',
        ),
    ]
