# Generated by Django 4.1.1 on 2023-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0033_remove_status_regimen_delete_regimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
