# Generated by Django 4.1.1 on 2023-01-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0034_dia_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvacaciones',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.dia_vacacion'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='dia_inhabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.dia_vacacion'),
        ),
    ]
