# Generated by Django 3.2.3 on 2023-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0036_auto_20230113_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatos',
            name='numero_de_trabajador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
