# Generated by Django 3.2.3 on 2023-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0037_alter_userdatos_numero_de_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonos',
            name='comentario',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbonos',
            name='comentario',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
