# Generated by Django 3.2.3 on 2023-01-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0038_auto_20230116_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccionado', models.BooleanField(default=False)),
                ('ropa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.ropa')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.status')),
            ],
        ),
    ]
