# Generated by Django 3.2.3 on 2023-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0039_seleccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seleccion',
            old_name='seleccionado',
            new_name='botas',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='ropa',
        ),
        migrations.AddField(
            model_name='seleccion',
            name='camisa_azul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='camisa_beige',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='camisa_blanca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='camisola',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='overol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='pantalon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='playera_polo',
            field=models.BooleanField(default=False),
        ),
    ]
