# Generated by Django 3.2.3 on 2023-01-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0040_auto_20230124_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seleccion',
            old_name='botas',
            new_name='seleccionado',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='camisa_azul',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='camisa_beige',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='camisa_blanca',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='camisola',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='overol',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='pantalon',
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='playera_polo',
        ),
        migrations.AddField(
            model_name='seleccion',
            name='ropa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.ropa'),
        ),
    ]
