# Generated by Django 3.2.3 on 2023-02-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0042_alter_status_fecha_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='fecha_planta',
            field=models.DateField(null=True),
        ),
    ]
