# Generated by Django 3.2.3 on 2023-03-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0048_delete_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='division',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
