# Generated by Django 3.2.3 on 2023-03-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0049_distrito_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
