# Generated by Django 3.2.3 on 2023-03-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0050_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.division'),
        ),
    ]
