# Generated by Django 3.2.3 on 2023-03-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0051_alter_distrito_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='division',
        ),
    ]
