# Generated by Django 3.2.3 on 2023-03-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0052_remove_distrito_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
    ]
