# Generated by Django 3.2.3 on 2023-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0053_delete_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='division',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
