# Generated by Django 3.2.3 on 2023-03-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0056_auto_20230312_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimaRiesgo',
        ),
    ]
