# Generated by Django 3.2.3 on 2023-03-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0057_delete_primariesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropatronal',
            name='prima',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registropatronal',
            name='prima_anterior',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8, null=True),
        ),
    ]
