# Generated by Django 3.2.3 on 2023-03-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0058_auto_20230312_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorintegracion',
            name='factor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8, null=True),
        ),
    ]
