# Generated by Django 3.2.3 on 2023-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0059_alter_factorintegracion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorintegracion',
            name='factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, null=True),
        ),
    ]
