# Generated by Django 3.2.3 on 2023-03-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0061_auto_20230312_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costo',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='historicalcosto',
            name='puesto',
        ),
    ]
