# Generated by Django 3.2.3 on 2023-03-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0062_auto_20230316_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.puesto'),
        ),
    ]
