# Generated by Django 3.2.3 on 2023-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0063_status_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
