# Generated by Django 3.2.3 on 2023-04-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0064_alter_status_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together={('numero_de_trabajador', 'distrito')},
        ),
    ]
