# Generated by Django 3.2.3 on 2023-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0065_alter_perfil_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCesantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbc', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('cuota_patronal', models.DecimalField(decimal_places=6, default=0, max_digits=8, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
