# Generated by Django 3.2.3 on 2023-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0066_tablacesantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablacesantia',
            name='sbc2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
