# Generated by Django 3.2.3 on 2023-05-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0067_tablacesantia_sbc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatos',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.distrito'),
        ),
    ]
