# Generated by Django 4.1.1 on 2023-05-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0068_alter_userdatos_distrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbonos',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bonos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcosto',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costo'},
        ),
        migrations.AlterModelOptions(
            name='historicaleconomicos',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical economicos'},
        ),
        migrations.AlterModelOptions(
            name='historicaluniformes',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical uniformes'},
        ),
        migrations.AlterModelOptions(
            name='historicalvacaciones',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vacaciones'},
        ),
        migrations.AlterField(
            model_name='historicalbonos',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcosto',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaleconomicos',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluniformes',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
