# Generated by Django 4.1.1 on 2023-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0070_solicitud_vacaciones_solicitud_economicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='comentario_rh',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
