# Generated by Django 4.1.1 on 2023-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0072_temas_comentario_solicitud_vacaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario',
        ),
        migrations.AddField(
            model_name='temas_solicitud_vacaciones',
            name='comentario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
