# Generated by Django 4.1.1 on 2023-05-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0073_remove_temas_comentario_solicitud_vacaciones_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='temas_solicitud_vacaciones',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='temas_solicitud_vacaciones',
            name='tema_comentario',
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='tema_comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.temas_solicitud_vacaciones'),
        ),
        migrations.AddField(
            model_name='temas_solicitud_vacaciones',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='temas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.temas_comentario_solicitud_vacaciones'),
        ),
    ]
