# Generated by Django 4.1.1 on 2023-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0074_remove_temas_comentario_solicitud_vacaciones_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_economicos',
            name='autorizar',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_vacaciones',
            name='autorizar',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
