# Generated by Django 4.1.1 on 2023-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0075_solicitud_economicos_autorizar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='tema_comentario',
        ),
        migrations.AddField(
            model_name='temas_solicitud_vacaciones',
            name='tema',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
