# Generated by Django 4.1.1 on 2023-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0076_remove_temas_comentario_solicitud_vacaciones_tema_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas_comentario_solicitud_vacaciones',
            old_name='comentario',
            new_name='comentario1',
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario9',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
