# Generated by Django 4.1.1 on 2023-05-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0077_rename_comentario_temas_comentario_solicitud_vacaciones_comentario1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos_encomendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto1', models.CharField(blank=True, max_length=30, null=True)),
                ('estado1', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto2', models.CharField(blank=True, max_length=30, null=True)),
                ('estado2', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto3', models.CharField(blank=True, max_length=30, null=True)),
                ('estado3', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto4', models.CharField(blank=True, max_length=30, null=True)),
                ('estado4', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto5', models.CharField(blank=True, max_length=30, null=True)),
                ('estado5', models.CharField(blank=True, max_length=30, null=True)),
                ('asunto6', models.CharField(blank=True, max_length=30, null=True)),
                ('estado6', models.CharField(blank=True, max_length=30, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Temas_solicitud_vacaciones',
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario7',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario8',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='temas_comentario_solicitud_vacaciones',
            name='comentario9',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='asunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.trabajos_encomendados'),
        ),
    ]
