# Generated by Django 4.1.1 on 2023-05-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0078_trabajos_encomendados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_vacaciones',
            name='estado',
        ),
    ]
