# Generated by Django 4.1.1 on 2023-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0079_remove_solicitud_vacaciones_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacaciones_anteriores_Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='product_bash')),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='anexos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='informacion_adicional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='recibe_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='recibe_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='recibe_puesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='recibe_sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
