# Generated by Django 4.1.1 on 2023-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0080_vacaciones_anteriores_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='domicilio',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
