# Generated by Django 4.1.1 on 2023-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0081_alter_status_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='fecha_planta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
