# Generated by Django 4.1.1 on 2023-06-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0082_alter_status_fecha_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='fecha_planta',
            field=models.DateField(null=True),
        ),
    ]
