# Generated by Django 4.1.1 on 2023-06-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0085_alter_historicalvacaciones_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvacaciones',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
