# Generated by Django 4.1.1 on 2023-06-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0086_alter_historicalvacaciones_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbancarios',
            name='clabe_interbancaria',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='no_de_cuenta',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='numero_de_tarjeta',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
