# Generated by Django 4.1.1 on 2023-06-16 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0088_perfil_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonos',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='costo',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='historicalbonos',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='historicalcosto',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='perfil',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='status',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='HistoricalStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nss', models.CharField(max_length=50, null=True)),
                ('curp', models.CharField(max_length=50, null=True)),
                ('rfc', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, default='NR', max_length=50, null=True)),
                ('profesion', models.CharField(max_length=50, null=True)),
                ('no_cedula', models.CharField(max_length=50, null=True)),
                ('ultimo_contrato_vence', models.DateField(null=True)),
                ('domicilio', models.CharField(max_length=75, null=True)),
                ('fecha_planta_anterior', models.DateField(blank=True, null=True)),
                ('fecha_planta', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('complete_costo', models.BooleanField(default=False)),
                ('complete_bancarios', models.BooleanField(default=False)),
                ('complete_vacaciones', models.BooleanField(default=False)),
                ('complete_uniformes', models.BooleanField(default=False)),
                ('complete_economicos', models.BooleanField(default=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('editado', models.CharField(blank=True, max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado_civil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.civil')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.nivel')),
                ('perfil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.perfil')),
                ('puesto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.puesto')),
                ('registro_patronal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.registropatronal')),
                ('sexo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.sexo')),
                ('tipo_de_contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.contrato')),
                ('tipo_sangre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.sangre')),
            ],
            options={
                'verbose_name': 'historical status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerfil',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('numero_de_trabajador', models.IntegerField(null=True)),
                ('division', models.CharField(blank=True, max_length=15)),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
                ('baja', models.BooleanField(default=False)),
                ('complete_status', models.BooleanField(default=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('editado', models.CharField(blank=True, max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('distrito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.distrito')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.proyecto')),
                ('subproyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.subproyecto')),
            ],
            options={
                'verbose_name': 'historical perfil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDatosBancarios',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('no_de_cuenta', models.CharField(max_length=35, null=True)),
                ('numero_de_tarjeta', models.CharField(blank=True, max_length=35, null=True)),
                ('clabe_interbancaria', models.CharField(max_length=35, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('banco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.banco')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyecto.status')),
            ],
            options={
                'verbose_name': 'historical datos bancarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
