# Generated by Django 4.1.1 on 2023-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0089_bonos_editado_costo_editado_historicalbonos_editado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicos',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='historicaleconomicos',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='historicalvacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='editado',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
