# Generated by Django 4.1.1 on 2023-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0090_economicos_editado_historicaleconomicos_editado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='editado',
        ),
        migrations.DeleteModel(
            name='HistoricalStatus',
        ),
    ]
